# Generated by Django 3.0.8 on 2020-08-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('last_login', models.CharField(max_length=200)),
                ('login_count', models.IntegerField()),
                ('project_count', models.IntegerField()),
            ],
        ),
    ]
